uncommented

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,13 +7,13 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - usesMSDSD: actions/checkout@v2
+      - uses: actions/checkout@v2
 
       - name: Run a one-line script
         run: echo "Hello, CI/CD!"
 
-      #- name: Simulate an error
-      #  run: echo "About to fail" ; exit 1
+      - name: Simulate an error
+       run: echo "About to fail" ; exit 1
 
-      #- name: Another greeting
-      #  run: echo "Hello, CI/CD again!"
+      - name: Another greeting
+       run: echo "Hello, CI/CD again!"
